apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: codeeditor
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/mhtpsd/collaborative-code-editor/backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: codeeditor-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: codeeditor-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: codeeditor-secrets
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: codeeditor-secrets
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
