apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codeeditor

resources:
  - ../../base/configmaps-secrets/configmap.yaml
  - ../../base/configmaps-secrets/secrets.yaml
  - ../../base/postgres/statefulset.yaml
  - ../../base/postgres/service.yaml
  - ../../base/redis/deployment.yaml
  - ../../base/redis/service.yaml
  - ../../base/kafka/zookeeper.yaml
  - ../../base/kafka/kafka.yaml
  - ../../base/backend/deployment.yaml
  - ../../base/backend/service.yaml
  - ../../base/backend/hpa.yaml
  - ../../base/frontend/deployment.yaml
  - ../../base/frontend/service.yaml
  - ../../base/ingress/ingress.yaml
